version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/fixadate
permissions:
  - object: /home/ubuntu/fixadate/
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 120
      runas: ubuntu
#  ValidateService:
#    - location: scripts/blueGreenDeploy.sh
#      timeout: 120
#      runas: ubuntu
#  ApplicationStart:
#    - location: scripts/deploy_no_stop.sh
#      timeout: 1000
#      runas: ubuntu