# name: Build and Test (Pull Request)
# on:
#   pull_request:
#     branches-ignore:
#       - 'HOTFIX'
#       - 'hotfix/**'
#     paths:
#       - '**'

# permissions: write-all

# jobs:
#   test:
#     uses: ./.github/workflows/common-steps.yml
#     secrets: inherit
