name: Build and Test (Pull Request)
on:
  pull_request:
    branches-ignore:
      - 'HOTFIX'
      - 'hotfix/**'
    paths:
      - '**'
permissions:
  checks: write
  pull-requests: write
  contents: write
jobs:
  test:
    uses: ./.github/workflows/common-steps.yml
    secrets: inherit
